### ISSUE TITLE
C4-Diagram

### ISSUE THREAD

**Issue by tkantar** [Alihanoa/Diem-explorer#1]
![Container_Diagramm](https://user-images.githubusercontent.com/67166563/117448705-5b084080-af3f-11eb-841d-7a5cc6e11326.png)

**Comment by dnmx9133** [comment]
![Blockchain_Explorer_C4_System_Context_Diagram_V2](https://user-images.githubusercontent.com/82523027/117550540-3eecc800-b041-11eb-90c5-494be8ff709a.jpg)

**Comment by kiview** [comment]
Just as a comment (without knowing your current state of work), the second diagram (system context) looks correct, the first one not. 

As correctly depicted in the context diagram the system your are modeling is the `Diem Explorer`, not `Diem`.

**Comment by tkantar** [comment]
![Container_Diagramm](https://user-images.githubusercontent.com/67166563/118283729-f82f2000-b4cf-11eb-881d-3ac9ee3a7783.png)

**Comment by dnmx9133** [comment]
The diagram above is our newest, reworked C4 Container Diagram
